name: openmm
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - ambertools=23.6
  - annotated-types=0.7.0
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arpack=3.9.1
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - biopython=1.86
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bson=0.5.10
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.22.0
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - cftime=1.6.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-option-group=0.5.6
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.14
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fftw=3.3.10
  - filelock=3.20.0
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - fsspec=2025.10.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.2.4
  - griddataformats=1.0.2
  - gsd=4.2.0
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.15.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcufft=11.4.1.4
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.1
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libpq=16.10
  - libprotobuf=5.28.3
  - librdkit=2024.03.5
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libtorch=2.6.0
  - libuuid=2.41.2
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - lxml=6.0.2
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mda-xdrlib=0.2.0
  - mdanalysis=2.10.0
  - mdtraj=1.11.0
  - mdurl=0.1.2
  - mistune=3.1.4
  - mmtf-python=1.1.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mrcfile=1.5.4
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf-fortran=4.6.2
  - netcdf4=1.7.2
  - networkx=3.5
  - nomkl=1.0
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - numexpr=2.14.1
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - ocl-icd-system=1.0.0
  - opencl-headers=2025.06.13
  - openff-amber-ff-ports=2025.09.0
  - openff-forcefields=2025.10.1
  - openff-interchange=0.4.9
  - openff-interchange-base=0.4.9
  - openff-nagl=0.5.4
  - openff-nagl-base=0.5.4
  - openff-nagl-models=2025.9.0
  - openff-toolkit=0.18.0
  - openff-toolkit-base=0.18.0
  - openff-units=0.3.1
  - openff-utilities=0.1.16
  - openjpeg=2.5.4
  - openmm=8.4.0
  - openmmforcefields=0.15.0
  - openssl=3.6.0
  - optree=0.18.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parmed=4.3.0
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pdbfixer=1.12
  - perl=5.32.1
  - pexpect=4.9.0
  - pillow=12.0.0
  - pint=0.24.4
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycairo=1.29.0
  - pycparser=2.22
  - pydantic=2.11.10
  - pydantic-core=2.33.2
  - pyedr=0.8.0
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - pytables=3.10.2
  - python=3.11.14
  - python-constraint=1.4.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.11.14
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytng=0.3.4
  - pytorch=2.6.0
  - pytorch-lightning=2.5.5
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rdkit=2024.03.5
  - readline=8.2
  - referencing=0.37.0
  - reportlab=4.4.4
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rlpycairo=0.4.0
  - rocm-core=7.0.2
  - rpds-py=0.29.0
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlalchemy=2.0.44
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sympy=1.14.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tidynamics=1.1.2
  - tinycss2=1.4.0
  - tinydb=4.8.2
  - tk=8.6.13
  - tomli=2.3.0
  - torchmetrics=1.8.2
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - validators=0.35.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - amberutils==21.0
      - edgembar==0.2
      - mmpbsa-py==16.0
      - packmol-memgen==2024.2.9
      - pdb4amber==22.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - sander==22.0
